const GET_DATA_REQUEST="GET_DATA_REQUEST";
const GET_PHONES__DATA_SUCCESS="GET_PHONES__DATA_SUCCESS";
const GET_DATA_FAILURE="GET_DATA_FAILURE";
const GET_TV__DATA_SUCCESS="GET_TV__DATA_SUCCESS";
const GET_LAPTOP__DATA_SUCCESS="GET_LAPTOP__DATA_SUCCESS"

export {GET_DATA_REQUEST,GET_DATA_FAILURE,GET_PHONES__DATA_SUCCESS,GET_TV__DATA_SUCCESS,GET_LAPTOP__DATA_SUCCESS}